services:
  - type: web
    name: wafer-fault-detection
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.app:app
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: 3.12.4

